### PR TITLE
feat: introduce esm and cjs support

### PR DESCRIPTION
**Pull request by n1ru4l**
I am following this comment:

https://github.com/d3/d3/issues/3469#issue-809713670

This should close https://github.com/sikanhe/gqtx/issues/3 (and also https://github.com/sikanhe/gqtx/pull/42)

~~See https://unpkg.com/browse/gqtx@0.8.1-a9325d31.0/ for a folder structure overview of the published package.~~
See https://unpkg.com/browse/gqtx@0.8.1-913ef0b2.0/ for a file directory overview.

### CODE REVIEW

**Comment by sikanhe** [comment]
LGTM

**Review by sikanhe — APPROVED** [review]

**Comment by n1ru4l** [comment]
Please not merge yet I still need to confirm out whether it works correctly with the most common use-cases

**Comment by sikanhe** [comment]
@n1ru4l feel free to merge when you have it working!

**Comment by n1ru4l** [comment]
Ok, it seems to work. It is a bit ugly though and all the files had to be moved to the package root... But it seems like its the only way to properly support both ESM and typescript in a backwards-compatible way until typescript introduces proper ESM support...

See https://unpkg.com/browse/gqtx@0.8.1-913ef0b2.0/ for a file directory overview.

Gonna leave this open for a few days if anyone has some more feedback. Otherwise, I will merge it probably some day on the weekend. Maybe @zth has something to add?

**Pull request merged**
