### PR TITLE
Relay Helpers

### PR DESCRIPTION
**Pull request by sikanhe**
- [x] Connection types and helpers to create connections
- [x] Node interface

Closes https://github.com/sikanhe/gqtx/issues/22

### CODE REVIEW

**Comment by sikanhe** [comment]
@n1ru4l Let me know if this helps remove some of the boilerplate you have in your project!

**Comment by n1ru4l** [comment]
import first from "lodash/first";
import last from "lodash/last";

```ts

type ConnectionObject<T> = {
  edges: { node: T; cursor: string }[];
  pageInfo: {
    hasNextPage: boolean;
    hasPreviousPage: boolean;
    startCursor: string;
    endCursor: string;
  };
};

export const buildConnectionObject = <T>(params: {
  listData: T[];
  amount: number;
  encodeCursor: (input: T) => string;
}): ConnectionObject<T> => {
  let hasNextPage = false;
  let listData = params.listData;
  if (listData.length > params.amount) {
    listData = listData.slice(0, params.amount - 1);
    hasNextPage = true;
  }

  const edges = listData.map((node) => ({
    cursor: params.encodeCursor(node),
    node,
  }));

  return {
    edges,
    pageInfo: {
      hasNextPage,
      hasPreviousPage: false,
      startCursor: first(edges)?.cursor || "",
      endCursor: last(edges)?.cursor || "",
    },
  };
};
```

I often use that function for building the actual connection objects. Do you think it could be a nice addition here?

**Comment by jeffreyyoung** [comment]
is there anything blocking this pr from getting merged?

(also thanks for the great library! 😀)

**Comment by n1ru4l** [comment]
I guess feedback is the missing thing for getting this merged :D

**Comment by sikanhe** [comment]
Haha @jeffreyyoung I have been on vacation lately and not writing any code. Will get this merged in the next couple weeks. IN the meantime like @n1ru4l said please feel free to try this branch!

**Comment by zth** [comment]
This is 😍 Looking forward to seeing this merged!

**Comment by sikanhe** [comment]
Merging this soon, will have a beta out

**Comment by jeffreyyoung** [comment]
I forked the relay helpers branch and have really been enjoying it! I like the api, and haven't encountered any bugs.

**Comment by sikanhe** [comment]
published under 0.8.0-beta

**Pull request merged**
